// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFFpmbKPdvHClxHn2JLUHby4NlMXqlZrM',
    appId: '1:723875432311:web:e825c3c4cf759c33e64372',
    messagingSenderId: '723875432311',
    projectId: 'calmaddict-123',
    authDomain: 'calmaddict-123.firebaseapp.com',
    storageBucket: 'calmaddict-123.firebasestorage.app',
    measurementId: 'G-87J2HPGYY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8mS_AeFbGFvOctZh470TvJlA-alSDiQQ',
    appId: '1:723875432311:android:3c14a9631c7c801de64372',
    messagingSenderId: '723875432311',
    projectId: 'calmaddict-123',
    storageBucket: 'calmaddict-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBnHTK2M-TEQJbahBnI--vUF_96GHzjVY',
    appId: '1:723875432311:ios:a25544d9dc5385e2e64372',
    messagingSenderId: '723875432311',
    projectId: 'calmaddict-123',
    storageBucket: 'calmaddict-123.firebasestorage.app',
    iosBundleId: 'com.example.calmAddictFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBnHTK2M-TEQJbahBnI--vUF_96GHzjVY',
    appId: '1:723875432311:ios:a25544d9dc5385e2e64372',
    messagingSenderId: '723875432311',
    projectId: 'calmaddict-123',
    storageBucket: 'calmaddict-123.firebasestorage.app',
    iosBundleId: 'com.example.calmAddictFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFFpmbKPdvHClxHn2JLUHby4NlMXqlZrM',
    appId: '1:723875432311:web:ad891e83b8954bc3e64372',
    messagingSenderId: '723875432311',
    projectId: 'calmaddict-123',
    authDomain: 'calmaddict-123.firebaseapp.com',
    storageBucket: 'calmaddict-123.firebasestorage.app',
    measurementId: 'G-7PZJ2P86SG',
  );
}
